FROM python:2.7

EXPOSE 5000

WORKDIR /app

ENV GOOGLE_APPLICATION_CREDENTIALS multi-user-dungeon-firebase-adminsdk-fi2hw-4a23306b15.json

ADD requirements.txt /app

RUN pip install -r requirements.txt
